# Generated by Django 5.1.7 on 2025-03-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField()),
                ('current_location_latitude', models.FloatField(blank=True, null=True)),
                ('current_location_longitude', models.FloatField(blank=True, null=True)),
                ('pickup_location_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_location_longitude', models.FloatField(blank=True, null=True)),
                ('dropoff_location_latitude', models.FloatField(blank=True, null=True)),
                ('dropoff_location_longitude', models.FloatField(blank=True, null=True)),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('total_duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trips',
            },
        ),
    ]
